### ISSUE TITLE
Transferring ownership

### ISSUE THREAD

**Issue by lukepighetti** [solid-software/hydrated#16]
I no longer use `hydrated` so I'd like to find someone to help keep it from bitrotting. Seems like a handful of people still use it.

**Comment by solid-software** [comment]
Hi @lukepighetti, first of all thanks for your work on it! We are using it on a couple of our projects and even wanted to create a PR, so if you are ok with it - please consider us for ownership transfer.

**Comment by lukepighetti** [comment]
Hey! So weird I was just thinking about this. I already gave someone else full maintenance rights. May I ask what your plans would be for it?

**Comment by solid-software** [comment]
Thanks for your quick answer, if this package is ok and this issue is no longer relevant, then we are pretty happy with it. 

What we thought about is to add an ability to inject custom data storage implementation (in our case SharedPreferences wrapper that adds some useful to our app functionality). Also that should help to write unit tests more easily.

**Comment by lukepighetti** [comment]
I have resisted modular storage systems for `HydratedSubject` because I believe it's power is in its simplicity, but I know others in the past have disagreed with me. Since I no longer use this package I will ask @mateusfccp to weigh in and I will leave the final decision up to him.

**Comment by mateusfccp** [comment]
@lukepighetti I don't see any problem in making modular storage systems for HydratedSubject, as long as
* The API doesn't change
* The user may still be able to use the package without making any configuration (defaulting to `shared_preferences`)

About the ownership transfer, I don't really use this plugin anymore (I used to have it in a project from the company I work to), so I'm only watching over new issues and PRs, I'm not actively maintaining the package.

If you think that @solid-software will make a better work of this, feel free to transfer to them.

**Comment by solid-software** [comment]
Thanks @lukepighetti, for uploads please use this email:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/40825054/84365716-8755f880-abda-11ea-8b5d-c4b395c9655d.png">

**Comment by lukepighetti** [comment]
```
We've sent an invitation email to hello@solid.software.
They'll be added as an uploader after they accept the invitation.
```
